# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    concat: "puppetlabs/concat"
    stdlib: "puppetlabs/stdlib"
    lvm: "puppetlabs/lvm"
    mount_core: "puppetlabs/mount_core"
    sysctl: "duritong/sysctl"
    systemd: "camptocamp/systemd"
  repositories:
    disks:
      repo: 'https://code.immerda.ch/immerda/puppet-modules/disks.git'
    rkhunter:
      repo: 'https://code.immerda.ch/immerda/puppet-modules/rkhunter.git'
    selinux:
      repo: 'https://code.immerda.ch/immerda/puppet-modules/selinux.git'
    user:
      repo: 'https://code.immerda.ch/immerda/puppet-modules/user.git'
