---
stages:
  - syntax
  - unit

image: ruby:2.7.1

cache:
  paths:
    - vendor/bundle

before_script:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - bundle -v
  - bundle install --without system_tests --path vendor/bundle --jobs $(nproc)

run syntax:
  stage: syntax
  tags:
    - container
  script:
    - bundle exec rake syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop
  variables:
    PUPPET_GEM_VERSION: '~> 6.0'

run parallel-spec puppet 6:
  stage: unit
  tags:
    - container
  script:
    - bundle exec rake parallel_spec
  variables:
    PUPPET_GEM_VERSION: '~> 6.0'

run parallel-spec puppet 5:
  stage: unit
  image: ruby:2.4.4
  tags:
    - container
  script:
    - bundle exec rake parallel_spec
  variables:
    PUPPET_GEM_VERSION: '~> 5.0'

